# See config.example.yml for documentation.
object_base: orig/GCDE08
object: sys/main.dol
hash: 588949393623f6d776c13ede196ab8c2aa16276b
symbols: config/GCDE08/symbols.txt
splits: config/GCDE08/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 10
