

// bhEff_E00_Mince
// bhEff_E00_DrawParticleSpr
// bhEff_E00_DrawParticlePly
// bhEff_E00_DropBlood
// bhEff_E00_Fire
// bhEff_E00_Acid
// bhEff_E00_AcidGenerator
// bhEff_E00_BloodBurst
// bhEff_E00_Blood
// bhEff_E00_Dust
// bhEff_E02_SandDust
// bhEff_E02_SandParticle
// bhEff_E02_SandParticle2
// bhEff_E03_Acid
// bhEff_E03_Shadow
// bhEff_E05_Blood
// bhEff_E06_Rinpun
// bhEff_E11_SearchLight
// bhEff_E11_SearchLightDraw
// hEff_E11_CheckCollisionPlayer
// bhEff_E16_LaserSight
// bhEff_E16_LaserSightDraw
// bhEff_E12_Fire
// bhEff_E12_FrameLiquid
// bhEff_E12_FloorBlood2
// bhEff_E12_FireSpark
// bhEff_E12_FireManager
// bhEff_E12_FireBurstDraw
// bhEff_E12_Fire2
// bhEff_E12_Fire3
// bhEff_E12_BintaEffControl
// bhEff_E13_Fluid
// bhEff_E14_Explosion
// bhEff_E14_Fire
// bhEff_E14_Fire2
// bhEff_E14_Mucus
// bhEff_E14_MucusDraw
// bhEff_DamagePoint
// bhEff_DamagePointDraw
// bhEff_Draw3DSprite
// bhEff_SetUVInfo
// bhEff_SetAlign
// bhEff_SetBaseColor
// bhClrEff_YG
