

// AllocOwork 
// AllocOworkOne 
// bhClrEff_RY 
// bhSetBloodPoolLnk  
// bhEff300 
// bhEff301 
// bhSetEffParticle  
// bhSetEffParticleMk2 
// bhEff302 
// bhEff_PtclSpriteDrawB
// bhEff_PtclLineDraw  
// bhEff303 
// bhCheckCamWall2D  
// rySetShadow 
// bhEff304 
// bhEff305 
// bhEff306 
// bhSetRapEff 
// bhEff307 
// bhEff307Drw 
// bhSetEffGunSpark  
// bhSetEffSpark 
// bhEff308 
// bhEff308Drw 
// ryLinerColor
// rySetEffBlood 
// bhEff309 
// bhEff309Drw 
// ryRapTexDrw 
// ryRapTexAnm 
// ryRapDspSet 
// ryRapAnmColSet 
// bhEff30a 
// bhEff349 
// rySetEffBlood2 
// bhEff30b 
// bhEff30bDrw 
// bhEff30c 
// bhEff30cDrw 
