

// bhInitEvent                            
// bhControlEvent                         
// bhEnd                                  
// bhIfelCk                               
// bhElseCk                               
// bhEndif                                
// dm0                                    
// bhCk                                   
// bhSet                                  
// bhCmpB                                 
// bhCmpW                                 
// bhSv                                   
// bhSvW                                  
// bhEvtOn                                
// bhCamSet                               
// bhCamSet2                              
// bhCamPauseSet                          
// bhMessageSet                           
// bhBgmOn                                
// bhBgmOff                               
// bhSeOn                                 
// bhSeOff                                
// bhBGSeOn                               
// bhBGSeOff                              
// bhUseItemCheck                         
// bhArmsItemCheck                        
// bhArmsItemChange                       
// bhPlItemLost                           
// bhUseItemClear                         
// bhPlItemCheck                          
// bhMovieStart                           
// bhMovieStop                            
// bhVoiceOn                              
// bhVoiceOff                             
// bhAdxCk                                
// bhAdxTimeCk                            
// bhCineSet                              
// bhWalAtariSet                          
// bhEtcAtariSet                          
// bhFlrAtariSet                          
// bhSubStatus                            
// bhMotionPauseSet                       
// bhMotionPauseSetPly                    
// bhInitMotionPause                      
// bhInitMotionPauseEx                    
// bhEffectSet                            
// bhEffectSensyaSet                      
// bhEffectKokuenSet                      
// bhDieCk                                
// bhItmCk                                
// bhObjLinkSet                           
// bhSetObjMotion                         
// bhSetDispObj                           
// bhSetDoorCall                          
// bhDieEventCk                           
// bhSetDebugLoopEx                       
// bhInitSetKage                          
// bhObjLinkSetPly                        
// bhSetNextRoomBgm                       
// bhSetNextRoomBgSe                      
// bhFootSeCall                           
// bhEneSetCk                             
// bhItmSetCk                             
// bhInitModelSet                         
// bhEtcAtariSet2                         
// bhLightSet                             
// bhWeaponSeCall                         
// bhYakkyouSet                           
// bhFadeSet                              
// bhRoomCaseNo                           
// bhFrameCheck                           
// bhCamInfoSet                           
// bhMaskSet                              
// bhLipSet                               
// bhMaskStart                            
// bhLipStart                             
// bhMutekiSetPl                          
// bhLookGsetPlStart                      
// bhLookGsetPlStop                       
// bhSoundFadeOut                         
// bhDefModelSet                          
// bhItmAspdSet                           
// bhEffDispSet                           
// bhEffAmbSet                            
// bhObjLinkSetObjEne                     
// bhObjLinkSetObjItem                    
// bhObjLinkSetEneItem                    
// bhObjLinkSetEneEne                     
// bhDelObjSe                             
// bhLightTypeSet                         
// bhFogColorSet                          
// bhEffectSandSet                        
// bhPlItemBlockCk                        
// bhEffBloodSet                          
// bhEffBloodPoolSet                      
// bhEffBloodPoolSet2                     
// bhCyoutenHenkeiSet                     
// bhCyoutenHenkeiStart                   
// bhFixEventCamPly                       
// bhObjLinkSetObjObj                     
// bhCamYureSet                           
// bhInitCamSet                           
// bhMesDispEndSet                        
// bhPadCheck                             
// bhTFrameCheck                          
// bhEventTimerClr                        
// bhCamCheck                             
// bhRandamSet                            
// bhEventSkipSet                         
// bhDelYakkyou                           
// bhObjAlphaSet                          
// bhCyodanSet                            
// bhHEffectSet                           
// bhObjLinkSetObjPly                     
// bhEffPush                              
// bhEffPop                               
// bhAreaSearchObj                        
// bhLightParameterCSet                   
// bhLightParameterStart 
// bhInitMidiSlotSet                      
// bh3dSoundFlagSet                       
// bhSoundVolumeSet                       
// bhLightParameterSet                    
// bhEneSeOn                              
// bhEneSeOff                             
// bhWalAtariSet2                         
// bhFlrAtariSet2                         
// bhMotionPosSetEnePly                   
// bhKageSwSet                            
// bhSoundPanSet                          
// bhInitPonySet                          
// bhCyoutenHenkeiSetEX                   
// bhCyoutenHenkeiStartEX 
// bhEasySESet                            
// bhSoundFlagReSet                       
// bhEffUVSet                             
// bhPlayerChangeSet                      
// bhPlayerPoisonCk                       
// bhAddObjSe                             
// bhRandTest                             
// bhEvtComSet                            
// bhZombieUpDieCk                        
// bhFacePauseSet                         
// bhFaceReSet                            
// bhEffModeSet                           
// bhEnemyHpUp                            
// bhFaceRep                              
// bhBGSeOff2                             
// bhBgmOff2                              
// bhBGSeOn2                              
// bhBgmOn2                               
// bhMovieCk                              
// bhSetItmMotion                         
// bhObjAspdSet                           
// bhPuruPuruFlagSet                      
// bhPuruPuruStart                        
// bhSubMapBusyCk                         
// bhMapSystemOn                          
// bhTrapDamageSet                        
// bhEvtLighterFireSet                    
// bhObjLinkSetPlyItem                    
// bhPlayerKaidanMotion                   
// bhEneRenderSet                         
// bhBgmOnEx                              
// bhBgmOn2Ex                             
// bhFogParameterCSet                     
// bhFogParameterStart                    
// bhEffUVSet2                            
// bhBGColorSet                           
// bhMovieTimeCk                          
// bhEffTypeSet                           
// bhPlayerPoison2Cr                      
// bhPlyHandChange                        
// bhHEffectSet2                          
// bhObjDposCk                            
// bhItemGetGet                           
// bhEtcAtariEnePosSet                    
// bhEtcAtariEvtPosSet                    
// bhRoomSoundCase                        
// bhItemPlToSBox                         
// bhItemSBoxToIBox                       
// bhGrdPosSet                            
// bhGrdPosMoveCSet                       
// bhGrdPosMoveStart                      
// bhEvtKill                              
// bhReTryPointSet                        
// bhPlyDposCk                            
// bhPlItemLostEx                         
// bhCyodanSetEx                          
// bhArmsItemSet                          
// bhItemGetGetEx                         
// bhEffectSandSetMatsumoto
// bhVoiceWait                            
// bhVoiceStart                           
// bhGameOverSet                          
// bhPlItemChangeM                        
// bhEffBakuDrmSet                        
// bhPlItemTamaSet                        
// bhEffClearEvt                          
// bhEvtTimerSet                          
// bhEneLookFlgSet                        
// bhReturnTitleEvt                       
// bhSyukanModeSet                        
// bhExGameItemInit                       
// bhEneLifeSetM                          
// bhEffSSizeSet                          
// bhEffLinkOffsetSet                     
// bhRankingCall                          
// bhCallSysSe                            
// bhSleep                                
// bhSleeping                             
// bhWhile                                
// bhEwhile                               
// bhEwhile2                              
// bhEvtNext                              
// bhComNext                              
// bhEvtEnd                               
// bhFor                                  
// bhNext                                 
// bhPlCtr                                
// Player_controll                        
// bhObjCtr                               
// Obj_controll                           
// bhSubCtr                               
// Sub_controll                           
// bhCommonCtr                            
// Common_controll                        
// bhLoadWork                             
// bhLoadWorkEx                           
// bhLoadWork2                            
// Event_init                             
// Event_exec                             
// bhEventScheduler2                      
// bhScenarioCheck                        
// bhFlagCk                               
// bhFlagSet                              
// bhChangeViewClip                       
// bhChangeViewClipRM                     
// bhChangeClipVolume                     
// bhChangeClipVolumeRM                   
