

// bhInitMap 
// bhSetMap 
// bhExitMap 
// bhReadMapData 
// MapCnvStatus2Flag 
// bhControlMap 
// MapPadMain 
// MapViewMain 
// MapLightMain 
// MapPaletteMain 
// MapCodeProcess 
// MapBoolSet 
// MapDrawMarker 
// MapDrawBackground 
// MapDrawSprite 
// MapGetFloorNo 
// MapPurgeTree 
// MapFuncInit 
// MapFuncAlloc 
// MapFuncFree 
// MapFuncDel 
// MapFuncIns 
// MapFuncExec 
// FsubMapDraw 
// FsubBackDraw 
// MapEntrySprite 
// FsprSpriteDraw 
// FsprSilhouetteDraw
// FsprArrowDraw 
// FsprArrowDraw2 
// MapEntryTask 
// FsubTaskMain 
// FtskMapWait 
// FtskMapExit 
// FtskMapRead 
// FtskMapNormal 
// FtskMapZoom 
// FsubGaugeDrawZ 
// FsubGaugeDrawX 
// FsubGaugeDraw 
// MapTagInit 
// MapTagEntry 
// MapTagConnect 
// MapTagCenter 
// MapDrawLine2 
// MapDrawLine 
// MapDrawFill 
// MapDrawPolyFill 
// MapDrawMessage 
// FsubZoomCursor 
// FsubZoomInfomation
// MapCnvArgb2Color 
// FsubZoomScreen 
// FsubCompass 
// FsubModeMessage 
// MapCncInit 
// MapCncGet 
// MapCnc 
// MapCncConnect 
// MapCheckNextMap 
// GetGameMode 
