

// bhInitPlayer
// bhSetPlayer
// bhInitRoomChangePlayer
// bhResetPlayer
// bhCheckMothEgg
// bhCheckSubPack
// bhStandPlayerMotion
// bhKaidanPlayerMotion
// bhFixPositionXYZ
// bhCheckPlayerKegaMotion 
// bhCheckEvtTimer 
// bhControlPlayer 
// bhCPM0_action 
// bhControlPlayerPad 
// bhCPM1_act_bas 
// bhCPM2_act_std 
// bhCPM2_act_srt 
// bhCPM2_act_sta 
// bhCPM2_act_wlk 
// bhCPM2_act_run 
// bhCPM2_act_bak 
// bhCPM2_act_bk2 
// bhCPM2_act_kdu 
// bhCPM2_act_kdd 
// bhCPM2_act_dnu 
// bhCPM2_act_dnd 
// bhCPM2_act_psh 
// bhCPM2_act_cro 
// bhCPM2_act_hsu 
// bhCPM2_act_hsd 
// bhCPM2_act_rpsh 
// bhCPM1_act_atk 
// bhCPM2_act_suw 
// bhCPM2_act_wpn 
// bhCPM2_act_wre 
// bhCPM2_act_atk 
// bhCPM2_act_rld 
// bhCPM2_act_knf 
// bhCPM0_damage 
// bhCPM0_die 
// bhCPM0_nage 
// bhCPM0_enedam 
// bhCPM0_enedie 
// bhCPM0_nothing 
// bhControlPlayerHead
// bhLookNearEnemy 
// bhSetHeadRotation 
// bhCalcHair 
// bhGetTransZ 
