

// StatusInit 
// ItemBoxInit 
// CursorMove 
// CursorSet 
// SpriteSet2D 
// ItemSort 
// ItemSet 
// KazuSet 
// ItemUse 
// SpriteH 
// SpriteUV 
// BGFadeIn 
// BGFadeOut 
// ItemTaskCheck 
// StatusMain 
// GetItem 
// MainCommand 
// StatusCancel 
// WeaponSet 
// ItemCommand 
// ArmsSet 
// WindowJyoutai 
// ItemCommandErase 
// ItemCombination 
// SidePackSet 
// TrigerSet 
// BulletSet 
// Use_00 
// Use_01 
// Use_02 
// Use_04 
// Use_05 
// Combi_00 
// Combi_01 
// Combi_02 
// Combi_03 
// Combi_04 
// Combi_05 
// Combi_99 
// ItemBox 
// ItemBoxChange 
// BorderLineSet 
// SpriteOnOff 
// NameChangeSet 
// AllItemInit 
// ExtraGameItemInit 
// ItemBoxIconSet 
// bhSearchBullet 
// CenterPositionInit 
// BgColorInit 
// CursorInit 
// ItemSearch 
// EraseItem 
// PushPalletBuffer 
// PopPalletBuffer 
// SbsureInit 
// PulseInit 
// PulseMain 
// PulseAnim 
// PulseFadeAnim 
// PulseHealAnim 
// PulsePoisonHealAnim
// Pulse00 
// MultiWindowBack 
// KazariAnim 
// DrawPoly2D 
// DispFadeInit 
// FadePolyDisp 
// StatusMapFlagInit 
