

// ikou 
// ikou3 
// NitenDir_ck 
// bhCdirCheck 
// bhEne_LeverCheck 
// bhDGCdirCheck 
// bhDGCdirCheck2 
// bhDGCdirCheck3 
// bhEne_AngleCheck 
// bhEne_GetTranslateMtn 
// bhEne_GetTranslateMtn2 
// bhEne_CalcPartsPos 
// bhKaidanAtrCheck
// bhEne_EnemyAtariCheck 
// bhEne_PosCheck 
// bhEne_SetBlood 
// bhEne_SetBlood2 
// bhEne_SetBlood3 
// bhEne_SetBlood4 
// bhEne_SetNikuhenEffect 
// bhEne_SetNikuhenEffect2
// bhEne_SetDFireEffect
// bhEne_SetDFireEffect2 
// bhEne_SetSanEffect
// bhEne_SetSanEffect2 
// bhEne_QuickSort
// bhEne_ChgMtn 
// bhEne_CollisionCheckWall 
// bhEne_CollisionCheckWall2
// bhEne_CheckDirWall 
// bhEne_CheckDirWall2 
// bhEne_CheckDirWall3 
// bhEne_CheckSideWall 
// bhEne_CheckSideWall2 
// bhEne_CheckSideWall3 
// bhEne_SetVibration 
// bhEne_PlayerSePlay 
// bhEne_HitCheckParts 
